In [4]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

# 문서 정의
docs = [
    "내가 좋아하는 사과",
    "내가 좋아하는 바나나",
    "동그란 사과 사과",
    "저는 과일이 좋아요"
]

# CountVectorizer로 단어 카운트 행렬 생성
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)
print(X)

# numpy 배열로 변환
doc_term_matrix = X.toarray()

# 단어 목록 확인
vocab = vectorizer.get_feature_names_out()

# 결과 출력
print("단어 목록 :", vocab)
print("")
print("문서-단어 행렬 : ")
print(doc_term_matrix)

  (0, 1)	1
  (0, 7)	1
  (0, 4)	1
  (1, 1)	1
  (1, 7)	1
  (1, 3)	1
  (2, 4)	2
  (2, 2)	1
  (3, 5)	1
  (3, 0)	1
  (3, 6)	1
단어 목록 : ['과일이' '내가' '동그란' '바나나' '사과' '저는' '좋아요' '좋아하는']

문서-단어 행렬 : 
[[0 1 0 0 1 0 0 1]
 [0 1 0 1 0 0 0 1]
 [0 0 1 0 2 0 0 0]
 [1 0 0 0 0 1 1 0]]


In [5]:
"""
문서 목록
docs = [
    "내가 좋아하는 사과",
    "내가 좋아하는 바나나",
    "동그란 사과 사과",
    "저는 과일이 좋아요"
]
"""

from numpy import dot
from numpy.linalg import norm

def cosine_similarity(A, B):
    return dot(A, B) / (norm(A)*norm(B))

for i in range(len(doc_term_matrix)):
    for j in range(i+1, len(doc_term_matrix)):
        print(f"문서{i+1}과 문서{j+1}의 유사도:")
        print(cosine_similarity(doc_term_matrix[i], doc_term_matrix[j]))
        print('--------------------')

문서1과 문서2의 유사도:
0.6666666666666667
--------------------
문서1과 문서3의 유사도:
0.5163977794943222
--------------------
문서1과 문서4의 유사도:
0.0
--------------------
문서2과 문서3의 유사도:
0.0
--------------------
문서2과 문서4의 유사도:
0.0
--------------------
문서3과 문서4의 유사도:
0.0
--------------------
